#!/usr/bin/env python3
import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import warnings
from copy import copy
from copy import deepcopy


# - Dockerfile converter ---------------------------------------------------------------------------


class Recipe:
    """
    taken and modified from https://github.com/singularityhub/singularity-cli

    source of class:
    https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/recipe.py

    a recipe includes an environment, labels, runscript or command,
    and install sequence. This object is interacted with by a Parser
    (intended to popualte the recipe with content) and a Writer (intended
    to write a recipe to file). The parsers and writers are located in
    parsers.py, and writers.py, respectively. The user is also free to use
    the recipe class to build recipes.

    Parameters
    ==========
    recipe: the original recipe file, parsed by the subclass either
            DockerParser or SingularityParser
    layer: the count of the layer, for human readability

    """

    def __init__(self, recipe=None, layer=1):
        self.cmd = None
        self.comments = []
        self.entrypoint = None
        self.environ = []
        self.files = []
        self.layer_files = {}
        self.install = []
        self.labels = []
        self.ports = []
        self.test = None
        self.volumes = []
        self.workdir = None
        self.layer = layer
        self.fromHeader = None

        self.source = recipe

    def __str__(self):
        """show the user the recipe object, along with the type. E.g.,

        [spython-recipe][source:Singularity]
        [spython-recipe][source:Dockerfile]

        """
        base = "[spython-recipe]"
        if self.source:
            base = "%s[source:%s]" % (base, self.source)
        return base

    def json(self):
        """return a dictionary version of the recipe, intended to be parsed
        or printed as json.

        Returns: a dictionary of attributes including cmd, comments,
                 entrypoint, environ, files, install, labels, ports,
                 test, volumes, and workdir, organized by layer for
                 multistage builds.
        """
        attributes = [
            "cmd",
            "comments",
            "entrypoint",
            "environ",
            "files",
            "fromHeader",
            "layer_files",
            "install",
            "labels",
            "ports",
            "test",
            "volumes",
            "workdir",
        ]

        result = {}

        for attrib in attributes:
            value = getattr(self, attrib)
            if value:
                result[attrib] = value

        return result

    def __repr__(self):
        return self.__str__()


class DockerParser:
    """
    taken and modified from https://github.com/singularityhub/singularity-cli

    source of class:
    https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/parsers/base.py
    https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/parsers/docker.py
    """

    name = "docker"

    def __init__(self, filename="Dockerfile", load=True):
        """a generic recipe parser holds the original file, and provides
        shared functions for interacting with files. If the subclass has
        a parse function defined, we parse the filename

        Parameters
        ==========
        filename: the recipe file to parse.
        load: if True, load the filename into the Recipe. If not loaded,
              the user can call self.parse() at a later time.

        """
        self.filename = filename
        self._run_checks()
        self.lines = []

        # Arguments can be used internally, active layer name and number
        self.args = {}
        self.active_layer = "spython-base"
        self.active_layer_num = 1

        # Support multistage builds
        self.recipe = {"spython-base": Recipe(self.filename)}

        if self.filename:
            # Read in the raw lines of the file
            with open(self.filename, "r") as filey:
                self.lines = filey.readlines()

            # If parsing function defined, parse the recipe
            if load:
                self.parse()

    def __str__(self):
        """show the user the recipe object, along with the type. E.g.,

        [spython-parser][docker]
        [spython-parser][singularity]

        """
        base = "[spython-parser]"
        if hasattr(self, "name"):
            base = "%s[%s]" % (base, self.name)
        return base

    def __repr__(self):
        return self.__str__()

    def _run_checks(self):
        """basic sanity checks for the file name (and others if needed) before
        attempting parsing.
        """
        if self.filename is not None:
            # Does the recipe provided exist?
            if not os.path.exists(self.filename):
                print("Cannot find %s, is the path correct?" % self.filename)
                sys.exit(1)

            # Ensure we carry fullpath
            self.filename = os.path.abspath(self.filename)

    def _split_line(self, line):
        """clean a line to prepare it for parsing, meaning separation
        of commands. We remove newlines (from ends) along with extra spaces.

        Parameters
        ==========
        line: the string to parse into parts

        Returns
        =======
        parts: a list of line pieces, the command is likely first

        """
        return [x.strip() for x in line.split(" ", 1)]

    def _multistage(self, fromHeader):
        """Given a from header, determine if we have a multistage build, and
        update the recipe parser active in case that we do. If we are dealing
        with the first layer and it's named, we also update the default
        name "spython-base" to be what the recipe intended.

        Parameters
        ==========
        fromHeader: the fromHeader parsed from self.from, possibly with AS
        """
        # Derive if there is a named layer
        match = re.search("AS (?P<layer>.+)", fromHeader, flags=re.I)
        if match:
            layer = match.groups("layer")[0].strip()

            # If it's the first layer named incorrectly, we need to rename
            if len(self.recipe) == 1 and list(self.recipe)[0] == "spython-base":
                self.recipe[layer] = deepcopy(self.recipe[self.active_layer])
                del self.recipe[self.active_layer]
            else:
                self.active_layer_num += 1
                self.recipe[layer] = Recipe(self.filename, self.active_layer_num)
            self.active_layer = layer
            print("Active layer #%s updated to %s" % (self.active_layer_num, self.active_layer))

    def _replace_from_dict(self, string, args):
        """Given a lookup of arguments, args, replace any that are found in
        the given string. This is intended to be used to substitute ARGs
        provided in a Dockerfile into other sections, e.g., FROM $BASE

        Parameters
        ==========
        string: an input string to look for replacements
        args: a dictionary to make lookups from

        Returns
        =======
        string: the string with replacements made
        """
        for key, value in args.items():
            if re.search("([$]" + key + "|[$][{]" + key + "[}])", string):
                string = re.sub("([$]" + key + "|[$]{" + key + "[}])", value, string)
        return string

    def parse(self):
        """parse is the base function for parsing the Dockerfile, and extracting
        elements into the correct data structures. Everything is parsed into
        lists or dictionaries that can be assembled again on demand.

        Environment: Since Docker also exports environment as we go,
                     we add environment to the environment section and
                     install

        Labels: include anything that is a LABEL, ARG, or (deprecated)
                maintainer.

        Add/Copy: are treated the same

        """
        parser = None
        previous = None

        for line in self.lines:
            parser = self._get_mapping(line, parser, previous)

            # Parse it, if appropriate
            if parser:
                parser(line)

            previous = line

        # Instantiated by ParserBase
        return self.recipe

    # Setup for each Parser

    def _setup(self, action, line):
        """replace the command name from the group, alert the user of content,
        and clean up empty spaces
        """
        print("[in]  %s" % line)

        # Replace ACTION at beginning
        line = re.sub("^%s" % action, "", line)

        # Handle continuation lines without ACTION by padding with leading space
        line = " " + line

        # Split into components
        return [x for x in self._split_line(line) if x not in ["", None]]

    # From Parser

    def _from(self, line):
        """get the FROM container image name from a FROM line. If we have
        already seen a FROM statement, this is indicative of adding
        another image (multistage build).

        Parameters
        ==========
        line: the line from the recipe file to parse for FROM
        recipe: the recipe object to populate.
        """
        fromHeader = self._setup("FROM", line)

        # Do we have a multistge build to update the active layer?
        self._multistage(fromHeader[0])

        # Now extract the from header, make args replacements
        self.recipe[self.active_layer].fromHeader = self._replace_from_dict(
            re.sub("AS .+", "", fromHeader[0], flags=re.I), self.args
        )

        if "scratch" in self.recipe[self.active_layer].fromHeader:
            print("scratch is no longer available on Docker Hub.")
        print("FROM %s" % self.recipe[self.active_layer].fromHeader)

    # Run and Test Parser

    def _run(self, line):
        """everything from RUN goes into the install list

        Parameters
        ==========
        line: the line from the recipe file to parse for FROM

        """
        line = self._setup("RUN", line)
        self.recipe[self.active_layer].install += line

    def _test(self, line):
        """A healthcheck is generally a test command

        Parameters
        ==========
        line: the line from the recipe file to parse for FROM

        """
        self.recipe[self.active_layer].test = self._setup("HEALTHCHECK", line)

    # Arg Parser

    def _arg(self, line):
        """singularity doesn't have support for ARG, so instead will issue
        a warning to the console for the user to export the variable
        with SINGULARITY prefixed at build.

        Parameters
        ==========
        line: the line from the recipe file to parse for ARG

        """
        line = self._setup("ARG", line)

        # Args are treated like envars, so we add them to install
        environ = self.parse_env([x for x in line if "=" in x])
        self.recipe[self.active_layer].install += environ

        # Try to extract arguments from the line
        for arg in line:
            # An undefined arg cannot be used
            if "=" not in arg:
                print(
                    "ARG is not supported for Singularity, and must be defined with "
                    "a default to be parsed. Skipping %s" % arg
                )
                continue

            arg, value = arg.split("=", 1)
            arg = arg.strip()
            value = value.strip()
            print("Updating ARG %s to %s" % (arg, value))
            self.args[arg] = value

    # Env Parser

    def _env(self, line):
        """env will parse a line that beings with ENV, indicative of one or
        more environment variables.

        Parameters
        ==========
        line: the line from the recipe file to parse for ADD

        """
        line = self._setup("ENV", line)

        # Extract environment (list) from the line
        environ = self.parse_env(line)

        # Add to global environment, run during install
        self.recipe[self.active_layer].install += environ

        # Also define for global environment
        self.recipe[self.active_layer].environ += environ

    def parse_env(self, envlist):
        """parse_env will parse a single line (with prefix like ENV removed) to
        a list of commands in the format KEY=VALUE For example:

        ENV PYTHONBUFFER 1 --> [PYTHONBUFFER=1]
        Docker: https://docs.docker.com/engine/reference/builder/#env
        """
        if not isinstance(envlist, list):
            envlist = [envlist]

        exports = []

        for env in envlist:
            pieces = re.split("( |\\\".*?\\\"|'.*?')", env)
            pieces = [p for p in pieces if p.strip()]

            while pieces:
                current = pieces.pop(0)

                if current.endswith("="):
                    # Case 1: ['A='] --> A=
                    nextone = ""

                    # Case 2: ['A=', '"1 2"'] --> A=1 2
                    if pieces:
                        nextone = pieces.pop(0)
                    exports.append("export %s%s" % (current, nextone))

                # Case 3: ['A=B']     --> A=B
                elif "=" in current:
                    exports.append("export " + current)

                # Case 4: ENV \\
                elif current.endswith("\\"):
                    continue

                # Case 5: ['A', 'B']  --> A=B
                else:
                    nextone = pieces.pop(0)
                    exports.append("export %s=%s" % (current, nextone))

        return exports

    # Add and Copy Parser

    def _copy(self, lines):
        """parse_add will copy multiple files from one location to another.
        This likely will need tweaking, as the files might need to be
        mounted from some location before adding to the image.
        The add command is done for an entire directory. It is also
        possible to have more than one file copied to a destination:
        https://docs.docker.com/engine/reference/builder/#copy
        e.g.: <src> <src> <dest>/
        """
        lines = self._setup("COPY", lines)

        for line in lines:
            # Take into account multistage builds
            layer = None
            if line.startswith("--from"):
                layer = line.strip("--from").split(" ")[0].lstrip("=")
                if layer not in self.recipe:
                    print("COPY requested from layer %s, but layer not previously defined." % layer)
                    continue

                # Remove the --from from the line
                line = " ".join([word for word in line.split(" ")[1:] if word])

            values = line.split(" ")
            topath = values.pop()
            for frompath in values:
                self._add_files(frompath, topath, layer)

    def _add(self, lines):
        """Add can also handle https, and compressed files.

        Parameters
        ==========
        line: the line from the recipe file to parse for ADD

        """
        lines = self._setup("ADD", lines)

        for line in lines:
            values = line.split(" ")
            frompath = values.pop(0)

            # Custom parsing for frompath

            # If it's a web address, add to install routine to get
            if frompath.startswith("http"):
                for topath in values:
                    self._parse_http(frompath, topath)

            # Add the file, and decompress in install
            elif re.search("[.](gz|gzip|bz2|xz)$", frompath.strip()):
                for topath in values:
                    self._parse_archive(frompath, topath)

            # Just add the files
            else:
                for topath in values:
                    self._add_files(frompath, topath)

    # File Handling

    def _add_files(self, source, dest, layer=None):
        """add files is the underlying function called to add files to the
        list, whether originally called from the functions to parse archives,
        or https. We make sure that any local references are changed to
        actual file locations before adding to the files list.

        Parameters
        ==========
        source: the source
        dest: the destiation
        """

        # Warn the user Singularity doesn't support expansion
        if "*" in source:
            print("Singularity doesn't support expansion, * found in %s" % source)

        # Warning if file/folder (src) doesn't exist
        if not os.path.exists(source) and layer is None:
            print("%s doesn't exist, ensure exists for build" % source)

        # The pair is added to the files as a list
        if not layer:
            self.recipe[self.active_layer].files.append([source, dest])

        # Unless the file is to be copied from a particular layer
        else:
            if layer not in self.recipe[self.active_layer].layer_files:
                self.recipe[self.active_layer].layer_files[layer] = []
            self.recipe[self.active_layer].layer_files[layer].append([source, dest])

    def _parse_http(self, url, dest):
        """will get the filename of an http address, and return a statement
        to download it to some location

        Parameters
        ==========
        url: the source url to retrieve with curl
        dest: the destination folder to put it in the image

        """
        file_name = os.path.basename(url)
        download_path = "%s/%s" % (dest, file_name)
        command = "curl %s -o %s" % (url, download_path)
        self.recipe[self.active_layer].install.append(command)

    def _parse_archive(self, targz, dest):
        """parse_targz will add a line to the install script to extract a
        targz to a location, and also add it to the files.

        Parameters
        ==========
        targz: the targz to extract
        dest: the location to extract it to

        """

        # Add command to extract it
        self.recipe[self.active_layer].install.append("tar -zvf %s %s" % (targz, dest))

        # Ensure added to container files
        return self._add_files(targz, dest)

    # Comments and Default

    def _comment(self, line):
        """Simply add the line to the install as a comment. This function is
        equivalent to default, but added in the case we need future custom
        parsing (meaning a comment is different from a line.

        Parameters
        ==========
        line: the line from the recipe file to parse to INSTALL

        """
        self.recipe[self.active_layer].install.append(line)

    def _default(self, line):
        """the default action assumes a line that is either a command (a
        continuation of a previous, for example) or a comment.

        Parameters
        ==========
        line: the line from the recipe file to parse to INSTALL
        """
        if line.strip().startswith("#"):
            return self._comment(line)
        self.recipe[self.active_layer].install.append(line)

    # Ports and Volumes

    def _volume(self, line):
        """We don't have logic for volume for Singularity, so we add as
        a comment in the install, and a metadata value for the recipe
        object

        Parameters
        ==========
        line: the line from the recipe file to parse to INSTALL

        """
        volumes = self._setup("VOLUME", line)
        if volumes:
            self.recipe[self.active_layer].volumes += volumes
        return self._comment("# %s" % line)

    def _expose(self, line):
        """Again, just add to metadata, and comment in install.

        Parameters
        ==========
        line: the line from the recipe file to parse to INSTALL

        """
        ports = self._setup("EXPOSE", line)
        if ports:
            self.recipe[self.active_layer].ports += ports
        return self._comment("# %s" % line)

    def _stopsignal(self, line):
        """Again, just add to metadata, and comment in install.

        Parameters
        ==========
        line: the line from the recipe file to parse STOPSIGNAL
        """
        return self._comment("# %s" % line)

    # Working Directory

    def _workdir(self, line):
        """A Docker WORKDIR command simply implies to cd to that location

        Parameters
        ==========
        line: the line from the recipe file to parse for WORKDIR

        """
        # Save the last working directory to add to the runscript
        workdir = self._setup("WORKDIR", line)
        workdir_mkdir = "mkdir -p %s" % ("".join(workdir))
        self.recipe[self.active_layer].install.append(workdir_mkdir)
        workdir_cd = "cd %s" % ("".join(workdir))
        self.recipe[self.active_layer].install.append(workdir_cd)
        self.recipe[self.active_layer].workdir = workdir[0]

    # Entrypoint and Command

    def _cmd(self, line):
        """_cmd will parse a Dockerfile CMD command

        eg: CMD /code/run_uwsgi.sh --> /code/run_uwsgi.sh.
            If a list is provided, it's parsed to a list.

        Parameters
        ==========
        line: the line from the recipe file to parse for CMD

        """
        cmd = self._setup("CMD", line)[0]
        self.recipe[self.active_layer].cmd = self._load_list(cmd)

    def _load_list(self, line):
        """load an entrypoint or command, meaning it can be wrapped in a list
        or a regular string. We try loading as json to return an actual
        list. E.g., after _setup, we might go from 'ENTRYPOINT ["one", "two"]'
        to '["one", "two"]', and this function loads as json and returns
        ["one", "two"]
        """
        try:
            line = json.loads(line)
        except Exception:
            pass
        return line

    def _entry(self, line):
        """_entrypoint will parse a Dockerfile ENTRYPOINT command

        Parameters
        ==========
        line: the line from the recipe file to parse for CMD

        """
        entrypoint = self._setup("ENTRYPOINT", line)[0]
        self.recipe[self.active_layer].entrypoint = self._load_list(entrypoint)

    # Labels

    def _label(self, line):
        """_label will parse a Dockerfile label

        Parameters
        ==========
        line: the line from the recipe file to parse for CMD

        """
        label = self._setup("LABEL", line)
        self.recipe[self.active_layer].labels += [label]

    # Main Parsing Functions

    def _get_mapping(self, line, parser=None, previous=None):
        """mapping will take the command from a Dockerfile and return a map
        function to add it to the appropriate place. Any lines that don't
        cleanly map are assumed to be comments.

        Parameters
        ==========
        line: the list that has been parsed into parts with _split_line
        parser: the previously used parser, for context

        Returns
        =======
        function: to map a line to its command group

        """

        # Split the command into cleanly the command and rest
        if not isinstance(line, list):
            line = self._split_line(line)

        # No line we will give function to handle empty line
        if not line:
            return None

        cmd = line[0].upper()

        mapping = {
            "ADD": self._add,
            "ARG": self._arg,
            "COPY": self._copy,
            "CMD": self._cmd,
            "ENTRYPOINT": self._entry,
            "ENV": self._env,
            "EXPOSE": self._expose,
            "FROM": self._from,
            "HEALTHCHECK": self._test,
            "RUN": self._run,
            "WORKDIR": self._workdir,
            "MAINTAINER": self._label,
            "VOLUME": self._volume,
            "LABEL": self._label,
            "STOPSIGNAL": self._stopsignal,
        }

        # If it's a command line, return correct function
        if cmd in mapping:
            return mapping[cmd]

        # If it's a continued line, return previous
        cleaned = self._clean_line(line[-1])
        previous = self._clean_line(previous)

        # if we are continuing from last
        if cleaned.endswith("\\") and parser or previous.endswith("\\"):
            return parser

        return self._default

    def _clean_line(self, line):
        """clean line will remove comments, and strip the line of newlines
        or spaces.

        Parameters
        ==========
        line: the string to parse into parts

        Returns
        =======
        line: a cleaned line

        """
        # A line that is None should return empty string
        line = line or ""
        return line.split("#")[0].strip()


class SingularityWriter:
    """
    taken and modified from https://github.com/singularityhub/singularity-cli

    source of class:
    https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/writers/base.py
    https://github.com/singularityhub/singularity-cli/blob/master/spython/main/parse/writers/singularity.py
    """

    name = "singularity"

    def __init__(self, recipe=None):
        """a writer base will take a recipe object (parser.base.Recipe) and
        provide helpers for writing to file.

        Parameters
        ==========
        recipe: the recipe instance to parse

        """
        self.recipe = recipe

    def __str__(self):
        """show the user the recipe object, along with the type. E.g.,

        [spython-writer][docker]
        [spython-writer][singularity]

        """
        base = "[spython-writer]"
        if hasattr(self, "name"):
            base = "%s[%s]" % (base, self.name)
        return base

    def __repr__(self):
        return self.__str__()

    def write(self, output_file=None, force=True):
        """convert a recipe to a specified format, and write to file, meaning
        we use the loaded recipe to write to an output file.
        If the output file is not specified, a temporary file is used.

        Parameters
        ==========
        output_file: the file to save to, not required (estimates default)
        force: if True, if file exists, over-write existing file

        """
        if output_file is None:
            output_file = self._get_conversion_outfile()

        # Cut out early if file exists and we aren't overwriting
        if os.path.exists(output_file) and not force:
            print("%s exists, and force is False." % output_file)
            sys.exit(1)

        # Do the conversion if function is provided by subclass
        if hasattr(self, "convert"):
            converted = self.convert()
            print("Saving to %s" % output_file)
            with open(output_file, "w") as filey:
                filey.writelines(converted)

    def validate(self):
        """validate that all (required) fields are included for the Docker
        recipe. We minimimally just need a FROM image, and must ensure
        it's in a valid format. If anything is missing, we exit with error.
        """
        if self.recipe is None:
            print("Please provide a Recipe() to the writer first.")
            sys.exit(1)

    def convert(self, runscript="", force=False):
        """docker2singularity will return a Singularity build recipe based on
        a the loaded recipe object. It doesn't take any arguments as the
        recipe object contains the sections, and the calling function
        determines saving / output logic.
        """
        self.validate()

        # Write single recipe that includes all layer
        recipe = []

        # Number of layers
        num_layers = len(self.recipe)
        count = 0

        # Write each layer to new file
        for stage, parser in self.recipe.items():
            # Set the first and active stage
            self.stage = stage

            # From header is required
            if parser.fromHeader is None:
                print("Singularity recipe requires a from header.")
                sys.exit(1)

            recipe += ["\n\n\nBootstrap: docker"]
            recipe += ["From: %s" % parser.fromHeader]
            recipe += ["Stage: %s\n\n\n" % stage]

            # TODO: stopped here - bug with files being found
            # Add global files, and then layer files
            recipe += self._create_section("files")
            for layer, files in parser.layer_files.items():
                recipe += self.create_keyval_section(files, "files", layer)

            # Sections with key value pairs
            recipe += self._create_section("labels")
            recipe += self._create_section("install", "post")
            recipe += self._create_section("environ", "environment")

            # If we are at the last layer, write the runscript
            if count == num_layers - 1:
                runscript = self._create_runscript(runscript, force)

                # If a working directory was used, add it as a cd
                if parser.workdir is not None:
                    runscript = ["cd " + parser.workdir] + [runscript]

                # Finish the recipe, also add as startscript
                recipe += self.finish_section(runscript, "runscript")
                recipe += self.finish_section(runscript, "startscript")

                if parser.prepare is not None:
                    recipe += self.finish_section(parser.prepare, "test")
            count += 1

        # Clean up extra white spaces
        recipe = "\n".join(recipe).replace("\n\n", "\n").strip("\n")
        return recipe.rstrip()

    def _create_runscript(self, default="", force=False):
        """create_entrypoint is intended to create a singularity runscript
        based on a Docker entrypoint or command. We first use the Docker
        ENTRYPOINT, if defined. If not, we use the CMD. If neither is found,
        we use function default.

        Parameters
        ==========
        default: set a default entrypoint, if the container does not have
                 an entrypoint or cmd.
        force: If true, use default and ignore Dockerfile settings
        """
        entrypoint = default

        # Only look at Docker if not enforcing default
        if not force:
            if self.recipe[self.stage].entrypoint is not None:
                # The provided entrypoint can be a string or a list
                if isinstance(self.recipe[self.stage].entrypoint, list):
                    entrypoint = " ".join(self.recipe[self.stage].entrypoint)
                else:
                    entrypoint = "".join(self.recipe[self.stage].entrypoint)

            if self.recipe[self.stage].cmd is not None:
                if isinstance(self.recipe[self.stage].cmd, list):
                    entrypoint = entrypoint + " " + " ".join(self.recipe[self.stage].cmd)
                else:
                    entrypoint = entrypoint + " " + "".join(self.recipe[self.stage].cmd)

        # Entrypoint should use exec
        if not entrypoint.startswith("exec"):
            entrypoint = "exec %s" % entrypoint

        # Should take input arguments into account
        if not re.search('"?[$]@"?', entrypoint):
            entrypoint = '%s "$@"' % entrypoint
        return entrypoint

    def _create_section(self, attribute, name=None, stage=None):
        """create a section based on key, value recipe pairs,
         This is used for files or label

        Parameters
        ==========
        attribute: the name of the data section, either labels or files
        name: the name to write to the recipe file (e.g., %name).
              if not defined, the attribute name is used.

        """

        # Default section name is the same as attribute
        if name is None:
            name = attribute

        # Put a space between sections
        section = ["\n"]

        # Only continue if we have the section and it's not empty
        try:
            section = getattr(self.recipe[self.stage], attribute)
        except AttributeError:
            print("Recipe does not have section for %s" % attribute)
            return section

        # if the section is empty, don't print it
        if not section:
            return section

        # Files
        if attribute in ["files", "labels"]:
            return self.create_keyval_section(section, name, stage)

        # An environment section needs exports
        if attribute in ["environ"]:
            return self.create_env_section(section, name)

        # Post, Setup
        return self.finish_section(section, name)

    def finish_section(self, section, name):
        """finish_section will add the header to a section, to finish the recipe
        take a custom command or list and return a section.

        Parameters
        ==========
        section: the section content, without a header
        name: the name of the section for the header

        """

        if not isinstance(section, list):
            section = [section]

        # Convert USER lines to change user
        lines = []
        for line in section:
            if re.search("^USER", line):
                username = line.replace("USER", "", 1).rstrip()
                line = "su - %s" % username + " # " + line
            lines.append(line)

        header = ["%" + name]
        return header + lines

    def create_keyval_section(self, pairs, name, layer):
        """create a section based on key, value recipe pairs,
         This is used for files or label

        Parameters
        ==========
        section: the list of values to return as a parsed list of lines
        name: the name of the section to write (e.g., files)
        layer: if a layer name is provided, name section
        """
        if layer:
            section = ["%" + name + " from %s" % layer]
        else:
            section = ["%" + name]
        for pair in pairs:
            section.append(" ".join(pair).strip().strip("\\"))
        return section

    def create_env_section(self, pairs, name):
        """environment key value pairs need to be joined by an equal, and
         exported at the end.

        Parameters
        ==========
        section: the list of values to return as a parsed list of lines
        name: the name of the section to write (e.g., files)

        """
        section = ["%" + name]
        for pair in pairs:
            section.append("export %s" % pair)
        return section


def convert_dockerfile_to_apptainer(in_docker_context, out_apptainer_file):
    for file in os.listdir(in_docker_context):
        if file == "Dockerfile":
            in_docker_file = remove_redundant_slashes(in_docker_context + "/" + file)
    recipeParser = DockerParser(in_docker_file)
    recipeWriter = SingularityWriter(recipeParser.recipe)
    recipeWriter.write(out_apptainer_file)


def remove_redundant_slashes(path):
    return path.replace("//", "/").replace("/./", "/")


# - compose converter ------------------------------------------------------------------------------


class ParsingError(Exception):

    def __init__(self, message="parsing error"):
        super().__init__(message)


def get_key_value(item):
    if ":" in item:
        if item.endswith(":"):
            key = item[:-1]
            value = None
        else:
            key_value_split = item.split(": ")
            if len(key_value_split) == 1:
                key = None
                value = key_value_split[0]
            elif len(key_value_split) == 2:
                key = key_value_split[0]
                value = key_value_split[1]
            else:
                raise ParsingError()
    else:
        key = None
        value = item
    return key, value


class YamlNode:

    def __init__(self, indentation, key, value, list_item):
        self.key = key
        self.value = value
        self.is_list_item = list_item

    def __str__(self):
        return f"{self.key=}, {self.value=}, {self.is_list_item=}"

    def __repr__(self):
        return self.__str__()


class Reader:

    def __init__(self, file_path):
        self.indentation = -1
        self.indentation_previous = -2
        self.file_path = file_path
        self.gen = self.create_gen()
        self.yn = None

    def create_gen(self):
        with open(self.file_path, "r") as f:
            is_list_item = False
            for n, line in enumerate(f, start=1):
                line = line[:-1]
                if line.isspace() or line == "":
                    continue
                self.indentation = 0
                for char in line:
                    if char == " ":
                        self.indentation += 1
                    else:
                        break
                item = line[self.indentation:]
                if item.startswith("#"):
                    continue
                if item.startswith("- "):
                    item = item[2:]
                    is_list_item = True
                key, value = get_key_value(item)
                yield YamlNode(self.indentation, key, value, is_list_item)
        while True:
            yield None

    def next(self):
        self.indentation_previous = self.indentation
        self.yn = next(self.gen)


def recurse(r, func):
    d = None
    r.next()
    ind_here = r.indentation
    while r.yn is not None:
        if ind_here == r.indentation:
            d = func(r, d)
        if ind_here > r.indentation:
            return d
        if ind_here < r.indentation_previous:
            continue
        r.next()
    return d


def helper_set_up_dict(d):
    if d is None:
        d = {}
    return d


def helper_set_up_list(d):
    if d is None:
        d = []
    return d


def helper_add_dict(r, d, func, key):
    d = helper_set_up_dict(d)
    if key is None:
        key = r.yn.key
    elif key != r.yn.key:
        raise ParsingError()
    if func is None:
        d[key] = r.yn.value
    else:
        d[key] = recurse(r, func)
    return d


def helper_add_list(r, d, func):
    d = helper_set_up_list(d)
    if func is None:
        d.append(r.yn.value)
    else:
        d.append(recurse(r, func))
    return d


def extract_key(r, d, func):
    if d is None:
        d = {}
    key = r.yn.key
    d[key] = recurse(r, func)
    return d


def helper_take_value_or_recurse(r, d, func, key):
    d = helper_set_up_dict(d)
    if r.yn.value is not None:
        value = r.yn.value
    else:
        value = recurse(r, func)
    d[key] = value
    return d


def state_build(r, d):
    if r.yn.key == "context":
        return helper_add_dict(r, d, None, "context")
    elif r.yn.key == "dockerfile":
        return helper_add_dict(r, d, None, "dockerfile")
    else:
        raise ParsingError()


def state_volumes(r, d):
    return helper_add_list(r, d, None)


def state_environment(r, d):
    if r.yn.key is None:
        key, sep, value = r.yn.value.partition("=")
        if sep:
            value = value.replace("\"", "").replace("'", "")
        d = helper_set_up_list(d)
        d.append((key, value if sep else None))
        return d
    r.yn.value = r.yn.value.replace("\"", "").replace("'", "")
    return helper_add_dict(r, d, None, None)


def state_dns(r, d):
    return helper_add_list(r, d, None)


def state_labels(r, d):
    return helper_add_dict(r, d, None, None)


def state_security_opt(r, d):
    return helper_add_list(r, d, None)


def state_x_apptainer(r, d):
    if r.yn.value in ["writable-tmpfs"]:
        r.yn.value = "--" + r.yn.value
    return helper_add_list(r, d, None)


def state_service(r, d):
    if r.yn.key == "build":
        return helper_take_value_or_recurse(r, d, state_build, "build")
    elif r.yn.key == "command":
        r.yn.value = r.yn.value.replace("$$", "$")
        r.yn.value = shlex.split(r.yn.value)
        return helper_add_dict(r, d, None, "command")
    elif r.yn.key == "image":
        return helper_add_dict(r, d, None, "image")
    elif r.yn.key == "entrypoint":
        r.yn.value = r.yn.value.replace("$$", "$")
        r.yn.value = shlex.split(r.yn.value)
        return helper_add_dict(r, d, None, "entrypoint")
    elif r.yn.key == "volumes":
        return helper_add_dict(r, d, state_volumes, "volumes")
    elif r.yn.key == "environment":
        return helper_add_dict(r, d, state_environment, "environment")
    elif r.yn.key == "hostname":
        return helper_add_dict(r, d, None, "hostname")
    elif r.yn.key == "working_dir":
        return helper_add_dict(r, d, None, "working_dir")
    elif r.yn.key == "dns":
        return helper_add_dict(r, d, state_dns, "dns")
    elif r.yn.key == "labels":
        return helper_add_dict(r, d, state_labels, "labels")
    elif r.yn.key == "security_opt":
        return helper_add_dict(r, d, state_security_opt, "security_opt")
    elif r.yn.key == "read_only":
        return helper_add_dict(r, d, None, "read_only")
    elif r.yn.key == "init":
        return helper_add_dict(r, d, None, "init")
    elif r.yn.key == "x-apptainer":
        return helper_add_dict(r, d, state_x_apptainer, "x-apptainer")
    else:
        raise ParsingError()


def state_services(r, d):
    return helper_add_dict(r, d, state_service, None)


def state_root(r, d):
    if r.yn.key == "version":
        r.next()
    return helper_add_dict(r, d, state_services, "services")


def command_to_list(d_service, args):
    l = ["apptainer"]
    if args.COMMAND in ("up", "run"):
        if d_service.get("entrypoint"):
            l.append("exec")
        else:
            l.append("run")
    x_apptainer = d_service.get("x-apptainer")
    if x_apptainer:
        l += x_apptainer
    for vol in d_service.get("volumes", []):
        l += ["--bind", vol]
    environment = d_service.get("environment")
    if environment:
        if isinstance(environment, dict):
            environment = list(environment.items())
        for k, v in environment:
            if v is not None:
                l += ["--env", k + "=" + v]
    hostname = d_service.get("hostname")
    if hostname:
        l += ["--hostname", hostname]
    working_dir = d_service.get("working_dir")
    if working_dir:
        l += ["--cwd", working_dir]
    dns = d_service.get("dns")
    if dns:
        l += ["--dns", ",".join(dns)]
    security_opt = d_service.get("security_opt")
    if security_opt:
        for opt in security_opt:
            if opt == "no-new-privileges":
                l += ["--security", "no_new_privs"]
            else:
                raise ParsingError()
    read_only = d_service.get("read_only")
    if read_only == "false":
        l += ["--writable-tmpfs"]
    init = d_service.get("init")
    if init == "false":
        l += ["--no-init"]
    image = d_service.get("image")
    if image:
        l.append("docker://" + image)
    entrypoint = d_service.get("entrypoint")
    if entrypoint:
        l += entrypoint
    command = d_service.get("command")
    if command:
        l += command
    return l


def command_to_str(d_service, args):
    s = ""
    prev = None
    for e in command_to_list(d_service, args):
        if prev == "--env":
            var, val = e.split("=")
            s += f"{var}='{val}' "
        else:
            s += e + " "
        prev = e
    s = s[:-1]
    return s


# - main -------------------------------------------------------------------------------------------


def parse_args():
    parser = argparse.ArgumentParser(prog="apptainer-compose", description="Apptainer Compose")
    parser.add_argument("-f", "--file", help="file")
    parser.add_argument("-v", "--verbose", action="store_true", help="verbose")
    parser.add_argument("--dry-run", action="store_true", help="dry run")
    parser.add_argument("-p", "--project-name", help="project name")
    parser.add_argument("--project-directory", help="project directory")
    parser.add_argument("--ansi", help="ansi color control")
    parser.add_argument("--parallel", help="max parallelism")
    parser.add_argument("--compatibility", action="store_true", help="backward compatibility mode")
    parser.add_argument("--all-resources", action="store_true", help="include all resources")
    subparsers = parser.add_subparsers(dest="COMMAND")
    up_parser = subparsers.add_parser("up", help="Start services")
    up_parser.add_argument("service_name", nargs="*", help="Service name")
    up_parser.add_argument("--pull", help="pull policy")
    up_parser.add_argument("--quiet-pull", action="store_true", help="quiet pull")
    up_parser.add_argument("--build", action="store_true", help="build before starting")
    up_parser.add_argument("--no-build", action="store_true", help="do not build")
    up_parser.add_argument("--quiet-build", action="store_true", help="quiet build")
    up_parser.add_argument("--abort-on-container-exit", action="store_true", help="stop all containers if any stopped")
    up_parser.add_argument("--abort-on-container-failure", action="store_true", help="stop all containers if any failed")
    up_parser.add_argument("--exit-code-from", help="return exit code of selected service")
    up_parser.add_argument("--no-color", action="store_true", help="monochrome output")
    up_parser.add_argument("--no-deps", action="store_true", help="do not start linked services")
    up_parser.add_argument("--no-recreate", action="store_true", help="do not recreate containers")
    up_parser.add_argument("--force-recreate", action="store_true", help="recreate containers")
    up_parser.add_argument("--always-recreate-deps", action="store_true", help="recreate dependent containers")
    up_parser.add_argument("--remove-orphans", action="store_true", help="remove containers for undefined services")
    up_parser.add_argument("-V", "--renew-anon-volumes", action="store_true", help="recreate anonymous volumes")
    up_parser.add_argument("-t", "--timeout", help="shutdown timeout in seconds")
    up_parser.add_argument("-y", "--yes", action="store_true", help="assume yes to prompts")
    subparsers.add_parser("build", help="Stop services")
    run_parser = subparsers.add_parser("run", help="Run custom command")
    run_parser.add_argument("service_name", help="Service name")
    run_parser.add_argument("run_command", nargs="*", help="Command and arguments to run")
    args = parser.parse_args()
    if args.file is None:
        args.file = "compose.yaml"
    if args.verbose:
        print(f"{args.file=}")
        print(f"{args.COMMAND=}")
    return args


def parse_compose(args):
    r = Reader(args.file)
    return recurse(r, state_root)


def execute(d_service, args):
    print(command_to_str(d_service, args), flush=True)
    if args.dry_run:
        return
    cmd_as_list = command_to_list(d_service, args)
    result = subprocess.run(cmd_as_list)
    if result.returncode != 0:
        sys.exit(result.returncode)


def main():
    args = parse_args()
    d = parse_compose(args)
    if args.COMMAND == "run":
        if args.service_name not in d["services"]:
            print(f"service {args.service_name} not found", file=sys.stderr)
            sys.exit(1)
        d_service = d["services"][args.service_name]
        if args.run_command:
            d_service["command"] = list(args.run_command)
        execute(d_service, args)
        return
    services = d["services"]
    if args.COMMAND == "up" and args.service_name:
        for name in args.service_name:
            if name not in services:
                print(f"service {name} not found", file=sys.stderr)
                sys.exit(1)
        services = {name: services[name] for name in services if name in args.service_name}
    for d_service in services.values():
        execute(d_service, args)


if __name__ == "__main__":
    main()
